#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"
COMPONENTS_OVERRIDE=""
ENV_FILE_SET=false

die() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

usage() {
  cat <<'EOF'
Usage: install.sh [--env PATH] [--only COMPONENTS]

Examples:
  sudo bash install.sh --only turboflare
  sudo bash install.sh --only beeline
  sudo bash install.sh --only turboflare,beeline,reality

--only overrides DEPLOY_COMPONENTS for this run. Configurations belonging to
components omitted from the list are left untouched; they are not removed.
For compatibility, a single positional argument is treated as the env path.
EOF
}

while (( $# > 0 )); do
  case "$1" in
    --env)
      (( $# >= 2 )) || die "--env requires a path"
      ENV_FILE="$2"
      ENV_FILE_SET=true
      shift 2
      ;;
    --env=*)
      ENV_FILE="${1#*=}"
      ENV_FILE_SET=true
      shift
      ;;
    --only)
      (( $# >= 2 )) || die "--only requires a component list"
      COMPONENTS_OVERRIDE="$2"
      shift 2
      ;;
    --only=*)
      COMPONENTS_OVERRIDE="${1#*=}"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    --*)
      die "Unknown option: $1"
      ;;
    *)
      [[ "${ENV_FILE_SET}" == false ]] || die "Unexpected argument: $1"
      ENV_FILE="$1"
      ENV_FILE_SET=true
      shift
      ;;
  esac
done

[[ "${EUID}" -eq 0 ]] || die "Run as root: sudo bash install.sh"
[[ -f "${ENV_FILE}" ]] || die "Environment file not found: ${ENV_FILE}. Run: cp .env.example .env"

missing_packages=()
if command -v nginx >/dev/null 2>&1; then
  if ! nginx -V 2>&1 | grep -q -- '--with-stream'; then
    missing_packages+=(libnginx-mod-stream)
  fi
else
  missing_packages+=(nginx libnginx-mod-stream)
fi
command -v openssl >/dev/null 2>&1 || missing_packages+=(openssl)
command -v envsubst >/dev/null 2>&1 || missing_packages+=(gettext-base)
command -v jq >/dev/null 2>&1 || missing_packages+=(jq)
command -v dig >/dev/null 2>&1 || missing_packages+=(dnsutils)

if (( ${#missing_packages[@]} > 0 )); then
  export DEBIAN_FRONTEND=noninteractive
  apt-get update
  apt-get install -y "${missing_packages[@]}"
fi

chmod 600 "${ENV_FILE}"

set -a
# shellcheck disable=SC1090
source "${ENV_FILE}"
set +a

declare -A ENABLED_COMPONENTS=()
parse_components() {
  local raw_components="$1"
  local component
  local -a requested_components

  IFS=',' read -r -a requested_components <<< "${raw_components}"
  for component in "${requested_components[@]}"; do
    component="${component//[[:space:]]/}"
    component="${component,,}"
    [[ -n "${component}" ]] || continue
    case "${component}" in
      turboflare|beeline|reality)
        ENABLED_COMPONENTS["${component}"]=1
        ;;
      *)
        die "Unsupported component: ${component}. Use turboflare, beeline and/or reality"
        ;;
    esac
  done
  (( ${#ENABLED_COMPONENTS[@]} > 0 )) || die "At least one deployment component must be enabled"
}

parse_components "${COMPONENTS_OVERRIDE:-${DEPLOY_COMPONENTS:-turboflare,reality}}"

component_enabled() {
  [[ -n "${ENABLED_COMPONENTS[$1]:-}" ]]
}

if component_enabled reality; then
  bash "${SCRIPT_DIR}/scripts/ensure-reality-credentials.sh" "${ENV_FILE}"
fi

render_args=(--env "${ENV_FILE}")
if [[ -n "${COMPONENTS_OVERRIDE}" ]]; then
  render_args+=(--only "${COMPONENTS_OVERRIDE}")
fi
bash "${SCRIPT_DIR}/scripts/render.sh" "${render_args[@]}"

# Reload values generated by ensure-reality-credentials.sh.
set -a
# shellcheck disable=SC1090
source "${ENV_FILE}"
set +a

TURBOFLARE_STREAM_MAP_FILE="${TURBOFLARE_STREAM_MAP_FILE:-${STREAM_MAP_FILE:-turboflare.map}}"
BEELINE_STREAM_MAP_FILE="${BEELINE_STREAM_MAP_FILE:-beeline.map}"
REALITY_STREAM_MAP_FILE="${REALITY_STREAM_MAP_FILE:-reality.map}"

BUILD_ROOT="${SCRIPT_DIR}/build"
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"

backup_and_install() {
  local source_file="$1"
  local destination_file="$2"
  local mode="$3"

  if [[ -e "${destination_file}" || -L "${destination_file}" ]]; then
    cp -a -- "${destination_file}" "${destination_file}.bak-${TIMESTAMP}"
  fi
  install -m "${mode}" "${source_file}" "${destination_file}"
}

enable_site() {
  local available="$1"
  local enabled="$2"

  if [[ -L "${enabled}" ]]; then
    return
  fi
  [[ ! -e "${enabled}" ]] || die "${enabled} exists and is not a symlink; refusing to overwrite it"
  ln -s "${available}" "${enabled}"
}

install_cover() {
  local cover_root="$1"
  local cover_title="$2"

  install -d -m 755 "${cover_root}"
  if [[ ! -e "${cover_root}/index.html" ]]; then
    cat > "${cover_root}/index.html" <<HTML
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>${cover_title}</title>
  <style>
    body{margin:0;min-height:100vh;display:grid;place-items:center;background:#0f172a;color:#e2e8f0;font:16px system-ui,sans-serif}
    main{padding:2rem;text-align:center}h1{font-size:1.5rem}p{color:#94a3b8}
  </style>
</head>
<body><main><h1>${cover_title}</h1><p>All systems operational.</p></main></body>
</html>
HTML
    chmod 644 "${cover_root}/index.html"
  fi
}

install_self_signed_certificate() {
  local domain="$1"
  local days="$2"
  local include_wildcard="${3:-false}"
  local ssl_dir="/etc/nginx/ssl/${domain}"
  local subject_alt_name="DNS:${domain}"

  if [[ "${include_wildcard}" == true ]]; then
    subject_alt_name+=",DNS:*.${domain}"
  fi

  install -d -m 700 "${ssl_dir}"
  if [[ ! -s "${ssl_dir}/origin.key" || ! -s "${ssl_dir}/origin.crt" ]]; then
    openssl req -x509 -nodes -newkey rsa:3072 -sha256 \
      -days "${days}" \
      -keyout "${ssl_dir}/origin.key" \
      -out "${ssl_dir}/origin.crt" \
      -subj "/CN=${domain}" \
      -addext "subjectAltName=${subject_alt_name}" \
      -addext "basicConstraints=critical,CA:FALSE" \
      -addext "keyUsage=critical,digitalSignature,keyEncipherment" \
      -addext "extendedKeyUsage=serverAuth"
  fi
  chmod 600 "${ssl_dir}/origin.key"
  chmod 644 "${ssl_dir}/origin.crt"
}

install -d -m 755 "${STREAM_MAP_DIR}"

if component_enabled turboflare; then
  TURBOFLARE_BUILD_DIR="${BUILD_ROOT}/turboflare/${DOMAIN}"
  TURBOFLARE_SITE_AVAILABLE="/etc/nginx/sites-available/${DOMAIN}.conf"
  TURBOFLARE_SITE_ENABLED="/etc/nginx/sites-enabled/${DOMAIN}.conf"

  install_self_signed_certificate "${DOMAIN}" "${ORIGIN_CERT_DAYS}" true
  install_cover "${COVER_ROOT}" "${COVER_TITLE}"
  backup_and_install "${TURBOFLARE_BUILD_DIR}/nginx-site.conf" "${TURBOFLARE_SITE_AVAILABLE}" 644
  enable_site "${TURBOFLARE_SITE_AVAILABLE}" "${TURBOFLARE_SITE_ENABLED}"
  backup_and_install "${TURBOFLARE_BUILD_DIR}/nginx-stream-map-entry.map" \
    "${STREAM_MAP_DIR}/${TURBOFLARE_STREAM_MAP_FILE}" 644
fi

if component_enabled beeline; then
  BEELINE_BUILD_DIR="${BUILD_ROOT}/beeline/${BEELINE_ORIGIN_DOMAIN}"
  BEELINE_SITE_AVAILABLE="/etc/nginx/sites-available/${BEELINE_ORIGIN_DOMAIN}.conf"
  BEELINE_SITE_ENABLED="/etc/nginx/sites-enabled/${BEELINE_ORIGIN_DOMAIN}.conf"

  if [[ "${BEELINE_ORIGIN_CERT_MODE}" == "selfsigned" ]]; then
    install_self_signed_certificate "${BEELINE_ORIGIN_DOMAIN}" "${BEELINE_ORIGIN_CERT_DAYS}" false
  else
    [[ -s "${BEELINE_ORIGIN_CERT}" ]] || die "Beeline origin certificate not found: ${BEELINE_ORIGIN_CERT}"
    [[ -s "${BEELINE_ORIGIN_KEY}" ]] || die "Beeline origin private key not found: ${BEELINE_ORIGIN_KEY}"
  fi

  install_cover "${BEELINE_COVER_ROOT}" "${BEELINE_COVER_TITLE}"
  install -d -m 755 "${BEELINE_ACME_ROOT}/.well-known/acme-challenge"
  backup_and_install "${BEELINE_BUILD_DIR}/nginx-site.conf" "${BEELINE_SITE_AVAILABLE}" 644
  enable_site "${BEELINE_SITE_AVAILABLE}" "${BEELINE_SITE_ENABLED}"
  backup_and_install "${BEELINE_BUILD_DIR}/nginx-stream-map-entry.map" \
    "${STREAM_MAP_DIR}/${BEELINE_STREAM_MAP_FILE}" 644
fi

if component_enabled reality; then
  REALITY_BUILD_DIR="${BUILD_ROOT}/reality"
  backup_and_install "${REALITY_BUILD_DIR}/nginx-stream-map-entry.map" \
    "${STREAM_MAP_DIR}/${REALITY_STREAM_MAP_FILE}" 644
fi

if ! nginx -T 2>&1 | grep -Fq "include ${STREAM_MAP_DIR}/*.map;"; then
  printf '\nACTION REQUIRED:\n'
  printf 'Add this line INSIDE the existing map $ssl_preread_server_name block:\n\n'
  printf '    include %s/*.map;\n\n' "${STREAM_MAP_DIR}"
  printf 'Do not create a second stream{} block and do not create a second public listen 443.\n'
  printf 'After editing nginx.conf, run this installer again.\n'
fi

nginx -t
systemctl reload nginx

printf '\nInstalled components:'
for component in turboflare beeline reality; do
  if component_enabled "${component}"; then
    printf ' %s' "${component}"
  fi
done
printf '\nCombined Xray inbounds: %s/shared/xray-inbounds.json\n' "${BUILD_ROOT}"
printf 'Components omitted from this run were not removed.\n'

if component_enabled turboflare; then
  printf '\nTurboFlare files: %s\n' "${TURBOFLARE_BUILD_DIR}"
  printf 'Direct origin check:\n'
  printf 'curl -4vk --resolve %s:443:%s https://%s/\n' "${DOMAIN}" "${ORIGIN_IP}" "${DOMAIN}"
fi

if component_enabled beeline; then
  printf '\nBeeline files: %s\n' "${BEELINE_BUILD_DIR}"
  printf 'Direct Beeline origin check:\n'
  printf 'curl -4vk --resolve %s:443:%s https://%s%s\n' \
    "${BEELINE_ORIGIN_DOMAIN}" "${ORIGIN_IP}" "${BEELINE_ORIGIN_DOMAIN}" "${BEELINE_XHTTP_PATH}"
  if [[ "${BEELINE_ORIGIN_CERT_MODE}" == "selfsigned" ]]; then
    printf 'Origin TLS is self-signed. Keep Beeline origin verification disabled until a trusted certificate is configured.\n'
  fi
fi

printf '\nExpected local listeners after assigning the generated inbounds to the node:\n'
listener_ports=(443)
if component_enabled turboflare; then
  listener_ports+=("${NGINX_INTERNAL_PORT}" "${XRAY_XHTTP_PORT}")
fi
if component_enabled beeline; then
  listener_ports+=("${BEELINE_NGINX_INTERNAL_PORT}" "${BEELINE_XRAY_XHTTP_PORT}")
fi
if component_enabled reality; then
  listener_ports+=("${REALITY_PORT}")
fi
listener_pattern=""
for listener_port in "${listener_ports[@]}"; do
  if [[ -n "${listener_pattern}" ]]; then
    listener_pattern+="|"
  fi
  listener_pattern+=":${listener_port}"
done
printf 'ss -lntp | grep -E "%s"\n' "${listener_pattern}"
